#!/bin/bash
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $BASE_DIR
TMP_FOLDER=/mnt/tmp/ZendeskTicketProcessor
mkdir -p $TMP_FOLDER 2>/dev/null

# Check requirements
if [ ! -r ../creds.txt ]
then
  echo "ERROR: You should have a creds.txt file on folder "`pwd`
  exit 1
fi
if [ -f $TMP_FOLDER ]
then
  echo "Creating tmp folder $TMP_FOLDER"
  mkdir -p $TMP_FOLDER
fi

# Constants
sleep_time=120
logfile=auto-ahtpanic-on-tickets.log

# Main
echo "Starting ticket watcher script: pausing ${sleep_time} seconds between runs."
echo "  Writing output log to $logfile"
echo "  Hit CTRL-C to break."
echo ""
while [ 1 ] ; do
  (date && php -f auto-ahtpanic-on-tickets.php && echo "==========") |tee -a $logfile;
  sleep $sleep_time;
done
